services:
  sherlocaster:
    build: .
    container_name: sherlocaster
    env_file:
      - ./config/twitch_token.env
    entrypoint: ["python", "-m", "app.main"]
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/data
      - ./logs:/logs
    environment:
      - TZ=Europe/Madrid

  sherlocaster-web:
    build: .
    container_name: sherlocaster-web
    entrypoint: []
    command: uvicorn app.web:app --host 0.0.0.0 --port 8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/data
      - ./logs:/logs
    environment:
      - TZ=Europe/Madrid
    ports:
      - "8000:8000"

