[Interface]
PrivateKey = GIDHBpf+oRUYvpEUvXsGqq7Li6hjoVdD+VQLqh1TSlM=
Address = 172.27.66.10/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = +t5LyqKsL5+ZGgxr2ycUEbHoD3yB2QDV3Tagt5m7Tkw=
Endpoint = homezgz.ddns.net:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

